name: CD

on:
  push:
    branches:
      - master

jobs:
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup AWS CLI
        uses: aws-actions/setup-aws-cli@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: Deploy to AWS Elastic Beanstalk
        uses: elasticbeanstalk/eb-deploy@v3
        with:
          app-name: my-app
          profile-name: ${{ secrets.AWS_PROFILE }}
          region: us-east-1
          verbose: true